source = ~/.config/hypr/font.conf

# --- Monitors ---
monitor=,preferred,auto,1

# --- Autostart ---
exec-once = waybar
exec-once = ~/.config/hypr/refresh.sh
exec-once = hyprpaper --config /home/jazaydcvbnmk1/.config/hypr/hyprpaper.conf
exec-once = swaync
exec-once = discord

# --- Input ---
input {
    kb_layout = us,ara
    kb_variant =
    kb_options = grp:win_space_toggle
    follow_mouse = 1
    sensitivity = 0.5
    accel_profile = flat
}

# --- Aesthetic & Colors ---
general {
    gaps_in = 5
    gaps_out = 10
    border_size = 0

    layout = dwindle
}

decoration {
    rounding = 0
    active_opacity = 0.95
    inactive_opacity = 0.85
    
    blur {
        enabled = true
        size = 5
        passes = 2
        new_optimizations = true
    }
}

# --- Animations ---
animations {
    enabled = true
    bezier = myBezier, 0.05, 0.9, 0.1, 1.05
    animation = windows, 1, 5, myBezier
    animation = windowsOut, 1, 5, default, popin 80%
    animation = border, 1, 10, default
    animation = fade, 1, 5, default
    animation = workspaces, 1, 5, default
}

# --- Hiding Layout Indicators & Logos ---
misc {
    disable_hyprland_logo = true
    force_default_wallpaper = 0
    background_color = 0x000000
    disable_splash_rendering = true
}

# --- Keybinds ---
$mainMod = SUPER
bind = SUPER SHIFT, A, exec, /home/jazaydcvbnmk1/.config/rofi-flatpak.sh
bind = $mainMod, I, exec, ~/.config/rofi-control-center.sh
bind = $mainMod, J, fullscreen,
bind = $mainMod, period, exec, ~/.config/rofi-emoji.sh
bind = $mainMod , F5, exec, ~/.config/hypr/refresh.sh
bind = $mainMod, W, exec, ~/.config/rofi-wifi.sh
bind = $mainMod SHIFT, F, exec, $HOME/.local/bin/rofi-font-changer
bind = $mainMod, ESCAPE, exec, ~/.config/hypr/powermenu.sh
bind = $mainMod, N, exec, kitty --class nmtui -e nmtui
bind = $mainMod, D, exec, discord
bind = $mainMod, S, exec, steam
bind = $mainMod, F, exec, firefox
bind = $mainMod, Q, exec, kitty
bind = $mainMod, P, pseudo
bind = $mainMod SHIFT, O, pin
bind = $mainMod, C, killactive,
bind = $mainMod, M, exit,
bind = $mainMod, E, exec, dolphin
bind = $mainMod SHIFT, V, exec, ~/.config/rofi-clipboard.sh
bind = $mainMod, R, exec, ~/.config/rofi-apps.sh
bind = , Print, exec, grim ~/Pictures/$(date +'%Y-%m-%d_%H-%M-%S').png && grim - | wl-copy
bind = $mainMod, Print, exec, grim -g "$(slurp)" ~/Pictures/$(date +'%Y-%m-%d_%H-%M-%S').png && grim -g "$(slurp)" - | wl-copy
bind = $mainMod, B, exec, ~/.config/rofi-bluetooth.sh
bind = $mainMod, left, movefocus, l
bind = $mainMod, right, movefocus, r
bind = $mainMod, up, movefocus, u
bind = $mainMod, down, movefocus, d
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, V, togglefloating
bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow
bind = $mainMod CTRL, left, resizeactive, -40 0
bind = $mainMod CTRL, right, resizeactive, 40 0
bind = $mainMod CTRL, up, resizeactive, 0 -40
bind = $mainMod CTRL, down, resizeactive, 0 40


#--- Cursor/mouse settings ---
env = XCURSOR_THEME,Bibata-Modern-Classic
env = XCURSOR_SIZE,20
cursor {
    no_hardware_cursors = false
}    
env = QT_QPA_PLATFORMTHEME,kde
xwayland {
}
    force_zero_scaling = true
input {
    # 1. Force a "flat" 1:1 movement profile (removes software drag/lag)
    accel_profile = flat
    sensitivity = 0.2  # Increase this (up to 1.0) if it still feels slow

    touchpad {
        natural_scroll = false
        disable_while_typing = false
        
        
        clickfinger_behavior = true
    }
}

device {
    name = *elan*
    disable_while_typing = false
    accel_profile = flat 
}

device {
    name = elan-trackpoint
    sensitivity = 0.3
}

# 5. Fixes Wayland visual lag (highly recommended for touchpads)
cursor {
    no_hardware_cursors = true
}
